# ==============================
# Application
# ==============================

APP_NAME = "Symora"
APP_VERSION = "0.1.0"

# ==============================
# Branding
# ==============================

COMPANY_NAME = "Symora Labs"

LOGO_PATH = "backend/app/assets/Logov1.png"

PRIMARY_COLOR = "#0F62FE"

SECONDARY_COLOR = "#0B1F3A"

# ==============================
# Reports
# ==============================

REPORT_TITLE = "Sigma Rule Assessment Report"

DEFAULT_REPORT_NAME = "symora_report.pdf"

REPORT_FOOTER = (
    "This report was automatically generated by "
    "the Symora Detection Engineering Platform."
)